### ISSUE TITLE
Can not see memcached server

### ISSUE THREAD

**Issue by crabvn** [koni/docker-php-nginx-mysql-memcached#2]
I can not find place to config site to memcached. Can you please instruct me the way to SEE memcached works on the localhost?

**Comment by koni** [comment]
@crabvn 

If you use memcached from localhost, you can add next on `docker-compose.yml`.

```yml
...
services:
  memcached:
    image: memcached:1.4
    ports:
      - "11212:11211"
...
```

In this example, I use the official memcached repository in dockerhub.
Normally it is unnecessary for development purposes, but if you want to write the configuration file please call the following URL.
https://hub.docker.com/_/memcached

For information on how to call memcached from PHP, refer to the following commit.
https://github.com/koni/docker-php-nginx-mysql-memcached/commit/19a851fd819388a7f6282a9e7e0f090418ef77a9
